name: Build

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build with dotnet
      run: dotnet build
    - name: Archive build results
      uses: actions/upload-artifact@v1
      with:
          name: Output
          path: bin/
